/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.bms.gui;

//import java.awt.Graphics;
//import java.awt.Image;
//import java.io.IOException;
//import java.net.MalformedURLException;
//import java.net.URL;
//import java.util.logging.Level;
//import javax.imageio.ImageIO;
import javax.swing.JInternalFrame;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

/**
 *
 * @author Shahab Afridi
 */
public class Bank extends javax.swing.JFrame {

    private static final Logger LOG = LogManager.getLogger(Bank.class);
    private JInternalFrame currentInternalFrame;

    /**
     * Creates new form Bank
     */
    public Bank() {
        initComponents();
//        try {
//            Image image = ImageIO.read(new URL("https://www.google.com/url?sa=i&url=https%3A%2F%2Funsplash.com%2Fs%2Fphotos%2Falone&psig=AOvVaw2KPkKNyaPWqYEQErZMkNwK&ust=1581168804949000&source=images&cd=vfe&ved=0CAIQjRxqFwoTCOiZsInHv-cCFQAAAAAdAAAAABAD"));
//            this.container.getGraphics().drawImage(image, 0, 0, this.getWidth(), this.getHeight(), container);
//            //this.container.getGraphics().drawImage(image, 0, 0, container);
//            LOG.info("so far seems ok");
//        } catch (IOException ex) {
//            LOG.error("while reading image {}", ex);
//        }
        //this.container.setLayout(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonsPanal = new javax.swing.JPanel();
        btnNewAccount = new javax.swing.JButton();
        btnDeposit = new javax.swing.JButton();
        btnWithDraw = new javax.swing.JButton();
        btnUpdateAccount = new javax.swing.JButton();
        btnTransfer = new javax.swing.JButton();
        btnCloseAcount = new javax.swing.JButton();
        container = new javax.swing.JDesktopPane();
        lblBank = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bank");

        buttonsPanal.setBackground(new java.awt.Color(51, 204, 255));

        btnNewAccount.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        btnNewAccount.setText("New Account");
        btnNewAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewAccountActionPerformed(evt);
            }
        });

        btnDeposit.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        btnDeposit.setText("Deposit");
        btnDeposit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepositActionPerformed(evt);
            }
        });

        btnWithDraw.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        btnWithDraw.setText("Withdraw");
        btnWithDraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWithDrawActionPerformed(evt);
            }
        });

        btnUpdateAccount.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        btnUpdateAccount.setText("Update Account");
        btnUpdateAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateAccountActionPerformed(evt);
            }
        });

        btnTransfer.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        btnTransfer.setText("Transfer");
        btnTransfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransferActionPerformed(evt);
            }
        });

        btnCloseAcount.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        btnCloseAcount.setText("Close Account");
        btnCloseAcount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseAcountActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout buttonsPanalLayout = new javax.swing.GroupLayout(buttonsPanal);
        buttonsPanal.setLayout(buttonsPanalLayout);
        buttonsPanalLayout.setHorizontalGroup(
            buttonsPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonsPanalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(buttonsPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDeposit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNewAccount, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                    .addComponent(btnWithDraw, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUpdateAccount, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTransfer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCloseAcount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        buttonsPanalLayout.setVerticalGroup(
            buttonsPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonsPanalLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(btnNewAccount)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDeposit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnWithDraw)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnUpdateAccount)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnTransfer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCloseAcount)
                .addContainerGap(172, Short.MAX_VALUE))
        );

        container.setBackground(new java.awt.Color(102, 204, 255));
        container.setPreferredSize(new java.awt.Dimension(541, 420));

        lblBank.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        lblBank.setForeground(new java.awt.Color(204, 204, 255));
        lblBank.setText("Defaulter Bank Limited");

        container.setLayer(lblBank, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout containerLayout = new javax.swing.GroupLayout(container);
        container.setLayout(containerLayout);
        containerLayout.setHorizontalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, containerLayout.createSequentialGroup()
                .addContainerGap(123, Short.MAX_VALUE)
                .addComponent(lblBank, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78))
        );
        containerLayout.setVerticalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerLayout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(lblBank, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenu1.setText("File");

        jMenuItem1.setText("jMenuItem1");
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("jMenuItem2");
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("jMenuItem3");
        jMenu1.add(jMenuItem3);

        jMenuItem4.setText("jMenuItem4");
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        jMenuItem5.setText("jMenuItem5");
        jMenu2.add(jMenuItem5);

        jMenuItem6.setText("jMenuItem6");
        jMenu2.add(jMenuItem6);

        jMenuItem7.setText("jMenuItem7");
        jMenu2.add(jMenuItem7);

        jMenuBar1.add(jMenu2);

        jMenu4.setText("jMenu4");
        jMenuBar1.add(jMenu4);

        jMenu5.setText("jMenu5");

        jMenu3.setText("jMenu3");
        jMenu5.add(jMenu3);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonsPanal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(container, javax.swing.GroupLayout.DEFAULT_SIZE, 601, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonsPanal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(container, javax.swing.GroupLayout.DEFAULT_SIZE, 424, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewAccountActionPerformed
        // TODO add your handling code here:
        this.lblBank.setVisible(false);
        this.disposeFtn();
        IfNewAccount newAccount = new IfNewAccount();
        newAccount.setVisible(true);
        currentInternalFrame = newAccount;
        container.add(newAccount);


    }//GEN-LAST:event_btnNewAccountActionPerformed

    private void btnDepositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepositActionPerformed
        // TODO add your handling code here:
        this.lblBank.setVisible(false);
        this.disposeFtn();
        IfDepositAmount newAccount = new IfDepositAmount();
        newAccount.setVisible(true);
        currentInternalFrame = newAccount;
        container.add(newAccount);

    }//GEN-LAST:event_btnDepositActionPerformed


    private void btnWithDrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWithDrawActionPerformed
        // TODO add your handling code here:
        this.lblBank.setVisible(false);
        this.disposeFtn();
        IfWithdrawAmount newAccount = new IfWithdrawAmount();
        newAccount.setVisible(true);
        currentInternalFrame = newAccount;
        container.add(newAccount);

    }//GEN-LAST:event_btnWithDrawActionPerformed

    private void btnUpdateAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateAccountActionPerformed
        // TODO add your handling code here
        this.lblBank.setVisible(false);
        this.disposeFtn();
        IfUpdateAccount newAccount = new IfUpdateAccount();
        newAccount.setVisible(true);
        currentInternalFrame = newAccount;
        container.add(newAccount);
    }//GEN-LAST:event_btnUpdateAccountActionPerformed

    private void btnTransferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransferActionPerformed
        // TODO add your handling code here:
        this.lblBank.setVisible(false);
        this.disposeFtn();
        IfTransfer newAccount = new IfTransfer();
        newAccount.setVisible(true);
        currentInternalFrame = newAccount;
        container.add(newAccount);
    }//GEN-LAST:event_btnTransferActionPerformed

    private void btnCloseAcountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseAcountActionPerformed
        // TODO add your handling code here:
        this.lblBank.setVisible(false);
        this.disposeFtn();
        IfCloseAccount newAccount = new IfCloseAccount();
        newAccount.setVisible(true);
        currentInternalFrame = newAccount;
        container.add(newAccount);
    }//GEN-LAST:event_btnCloseAcountActionPerformed

    private void disposeFtn() {
        if (currentInternalFrame != null) {
            currentInternalFrame.dispose();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bank().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCloseAcount;
    private javax.swing.JButton btnDeposit;
    private javax.swing.JButton btnNewAccount;
    private javax.swing.JButton btnTransfer;
    private javax.swing.JButton btnUpdateAccount;
    private javax.swing.JButton btnWithDraw;
    private javax.swing.JPanel buttonsPanal;
    private javax.swing.JDesktopPane container;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JLabel lblBank;
    // End of variables declaration//GEN-END:variables
}
