/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.bms.gui;

import edu.bms.ex.AccountNumberNotFountException;
import edu.bms.ex.InvalidNumberException;
import edu.bms.gui.validators.IValidator;
import edu.bms.gui.validators.NumberValidator;
import edu.bms.service.IAccountService;
import edu.bms.service.impl.AccountService;
import edu.bms.util.Constants;
import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.dom4j.Element;
import org.dom4j.io.SAXReader;

/**
 *
 * @author Shahab Afridi
 */
public class IfDepositAmount extends javax.swing.JInternalFrame {
    
    private static final Logger LOG;
    private static IValidator numberValidator;
    private static IAccountService accountService;

    /**
     * Creates new form DepositAmount
     */
    
    static {
        LOG = LogManager.getLogger(Bank.class);
        numberValidator = new NumberValidator();
        accountService = new AccountService();
    }
    
    public IfDepositAmount() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDAmountAccountDeposit = new javax.swing.JButton();
        PanalDepsitAmount = new javax.swing.JPanel();
        lblDAmountAccountHolderName = new javax.swing.JLabel();
        tfDAmountAccountHolderName = new javax.swing.JTextField();
        lblDAmountBalance = new javax.swing.JLabel();
        tfDAmountBalance = new javax.swing.JTextField();
        lblDAmountToDeposit = new javax.swing.JLabel();
        tfDAmountToDeposit = new javax.swing.JTextField();
        lblDAmountAccountNo = new javax.swing.JLabel();
        tfDAmountAccountNo = new javax.swing.JTextField();
        btnDAmountAccountSearch = new javax.swing.JButton();
        lblDtAmountInvalidResult = new javax.swing.JLabel();
        tfDAmountPhoneNumber = new javax.swing.JTextField();
        lblDAmountPhoneNumber = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Deposit Amount");
        setPreferredSize(new java.awt.Dimension(541, 420));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        btnDAmountAccountDeposit.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnDAmountAccountDeposit.setText("Deposit");
        btnDAmountAccountDeposit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDAmountAccountDepositActionPerformed(evt);
            }
        });

        PanalDepsitAmount.setBackground(new java.awt.Color(0, 204, 153));

        lblDAmountAccountHolderName.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblDAmountAccountHolderName.setText("Account Holder Name :");

        tfDAmountAccountHolderName.setEditable(false);
        tfDAmountAccountHolderName.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        lblDAmountBalance.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblDAmountBalance.setText("Balance : ");

        tfDAmountBalance.setEditable(false);
        tfDAmountBalance.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        lblDAmountToDeposit.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblDAmountToDeposit.setText("Amount  To Deposit :");

        tfDAmountToDeposit.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        lblDAmountAccountNo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblDAmountAccountNo.setText("Account Number :");

        tfDAmountAccountNo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        tfDAmountAccountNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfDAmountAccountNoKeyTyped(evt);
            }
        });

        btnDAmountAccountSearch.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnDAmountAccountSearch.setText("Search");
        btnDAmountAccountSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDAmountAccountSearchActionPerformed(evt);
            }
        });

        lblDtAmountInvalidResult.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblDtAmountInvalidResult.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        tfDAmountPhoneNumber.setEditable(false);
        tfDAmountPhoneNumber.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        lblDAmountPhoneNumber.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblDAmountPhoneNumber.setText("Phone Number :");

        javax.swing.GroupLayout PanalDepsitAmountLayout = new javax.swing.GroupLayout(PanalDepsitAmount);
        PanalDepsitAmount.setLayout(PanalDepsitAmountLayout);
        PanalDepsitAmountLayout.setHorizontalGroup(
            PanalDepsitAmountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanalDepsitAmountLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(PanalDepsitAmountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanalDepsitAmountLayout.createSequentialGroup()
                        .addComponent(lblDtAmountInvalidResult, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(PanalDepsitAmountLayout.createSequentialGroup()
                        .addGroup(PanalDepsitAmountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanalDepsitAmountLayout.createSequentialGroup()
                                .addComponent(lblDAmountAccountNo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                                .addComponent(tfDAmountAccountNo, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnDAmountAccountSearch))
                            .addGroup(PanalDepsitAmountLayout.createSequentialGroup()
                                .addGroup(PanalDepsitAmountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDAmountAccountHolderName)
                                    .addComponent(lblDAmountBalance))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(PanalDepsitAmountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfDAmountBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfDAmountAccountHolderName, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(53, 53, 53)))
                        .addContainerGap(69, Short.MAX_VALUE))
                    .addGroup(PanalDepsitAmountLayout.createSequentialGroup()
                        .addGroup(PanalDepsitAmountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(PanalDepsitAmountLayout.createSequentialGroup()
                                .addComponent(lblDAmountToDeposit)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tfDAmountToDeposit, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanalDepsitAmountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(PanalDepsitAmountLayout.createSequentialGroup()
                                    .addComponent(lblDAmountPhoneNumber)
                                    .addGap(222, 222, 222))
                                .addGroup(PanalDepsitAmountLayout.createSequentialGroup()
                                    .addGap(139, 139, 139)
                                    .addComponent(tfDAmountPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        PanalDepsitAmountLayout.setVerticalGroup(
            PanalDepsitAmountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanalDepsitAmountLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(PanalDepsitAmountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDAmountAccountNo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfDAmountAccountNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDAmountAccountSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDtAmountInvalidResult, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(PanalDepsitAmountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDAmountAccountHolderName, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfDAmountAccountHolderName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanalDepsitAmountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfDAmountBalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDAmountBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanalDepsitAmountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDAmountPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfDAmountPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanalDepsitAmountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDAmountToDeposit, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfDAmountToDeposit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDAmountAccountDeposit, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(205, 205, 205))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanalDepsitAmount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanalDepsitAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDAmountAccountDeposit, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        // TODO add your handling code here:
        int selection = JOptionPane.showConfirmDialog(null, "Are You Sure ?", "Warning", JOptionPane.YES_NO_OPTION);
        if (selection == JOptionPane.YES_OPTION) {
            this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        } else {
            this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        }
    }//GEN-LAST:event_formInternalFrameClosing

    private void btnDAmountAccountDepositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDAmountAccountDepositActionPerformed
        // TODO add your handling code here:
        boolean validatedSuccessfully = true;
        
        LOG.info(this.lblDAmountAccountNo.getText()+""+this.tfDAmountAccountNo.getText());
        LOG.info(this.lblDAmountAccountHolderName.getText()+""+this.tfDAmountAccountHolderName.getText());
        LOG.info(this.lblDAmountBalance.getText()+""+this.tfDAmountBalance.getText());
        LOG.info(this.lblDAmountToDeposit.getText()+""+this.tfDAmountToDeposit.getText());
        
        
        try {
            this.numberValidator.validateInitialDeposit(this.tfDAmountToDeposit.getText());
        } catch(InvalidNumberException excep){
            validatedSuccessfully = false;
            JOptionPane.showMessageDialog(null, "deposit amount must be in fraction",
                    "Wrong Entry",0);
        }
        
        
        if (validatedSuccessfully) {
           double amount = this.accountService.deposit(Long.parseLong(
                    this.tfDAmountAccountNo.getText()), 
                    Double.parseDouble(this.tfDAmountToDeposit.getText()));
           LOG.info("the total balance is : "+amount);
           this.tfDAmountBalance.setText(""+amount);
           JOptionPane.showMessageDialog(null, "Amount deposited Successfully ",
                    "Wrong Entry",JOptionPane.OK_OPTION);
           this.tfDAmountAccountNo.setText("");
           this.tfDAmountAccountHolderName.setText("");
           this.tfDAmountBalance.setText("");
           this.tfDAmountPhoneNumber.setText("");
           this.tfDAmountToDeposit.setText("");
        }
    }//GEN-LAST:event_btnDAmountAccountDepositActionPerformed

    private void tfDAmountAccountNoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfDAmountAccountNoKeyTyped
        // TODO add your handling code here:
        if (!Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_tfDAmountAccountNoKeyTyped

    private void btnDAmountAccountSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDAmountAccountSearchActionPerformed
        // TODO add your handling code here:
        try {
            this.numberValidator.validateAccountNumber(this.tfDAmountAccountNo.getText());
        } catch(InvalidNumberException ine) {
            this.lblDtAmountInvalidResult.setText("Input is Invalid");
            this.lblDtAmountInvalidResult.setForeground(Color.red);
        }
        
        
        try {
            Element account = this.accountService.findAccountElement(Long.parseLong(
                    this.tfDAmountAccountNo.getText()));
            this.tfDAmountAccountHolderName.setText(((Element) account.selectNodes(
                    Constants.EL_ACCOUNT_HOLDER).get(0)).getText());
            this.tfDAmountBalance.setText(((Element) account.selectNodes(
                    Constants.EL_BALANCE).get(0)).getText());
            LOG.info(((Element)account.selectNodes(
                    Constants.EL_BALANCE).get(0)).getText());
            this.tfDAmountPhoneNumber.setText(((Element)account.selectNodes(
                    Constants.EL_PHONE_NUMBER).get(0)).getText());
            
        } catch(AccountNumberNotFountException annfe){
            
        }
        
        
        //this.tfDAmountAccountHolderName.setText(title);
    }//GEN-LAST:event_btnDAmountAccountSearchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanalDepsitAmount;
    private javax.swing.JButton btnDAmountAccountDeposit;
    private javax.swing.JButton btnDAmountAccountSearch;
    private javax.swing.JLabel lblDAmountAccountHolderName;
    private javax.swing.JLabel lblDAmountAccountNo;
    private javax.swing.JLabel lblDAmountBalance;
    private javax.swing.JLabel lblDAmountPhoneNumber;
    private javax.swing.JLabel lblDAmountToDeposit;
    private javax.swing.JLabel lblDtAmountInvalidResult;
    private javax.swing.JTextField tfDAmountAccountHolderName;
    private javax.swing.JTextField tfDAmountAccountNo;
    private javax.swing.JTextField tfDAmountBalance;
    private javax.swing.JTextField tfDAmountPhoneNumber;
    private javax.swing.JTextField tfDAmountToDeposit;
    // End of variables declaration//GEN-END:variables
}
